### ISSUE TITLE
19" Outdoor-Rack gesucht

### ISSUE THREAD

**Issue by tscharly** [tscharly/c-mobile#7]
Wir suchen für die Reaktivierung unseres Dachstandortes @c-base einen outdoor 19" Schrank, Größe zweitrangig, dafür gern günstig :P
Kennt wer wen, der wen kennt? Oder wen, der Mobilfunkinstallation macht und an ausrangiertes Zeug rankommt?
@laf0rge @33dbm @freifunk-berlin @neeels

**Comment by laf0rge** [comment]
On Fri, Mar 29, 2024 at 06:07:18AM -0700, tscharly wrote:

> Oder wen, der Mobilfunkinstallation macht und an ausrangiertes Zeug rankommt?

leider nein.
Im Mobilfunk hast Du normalerweise keine 19" Outdoor-Gehaeuse.  Die Geraete fuer drausen (radio heads / radio units) sind an sich bereits IP6x, passiv gekuehlt und outdoor-faehig.  Und die Geraete fuer Drinnen (Baseband, ...) sind dann 19", aber da braucht es kein outdoor-gehaeuse. Die stehen dann in einem echten Gebaeude oder zumindest Container.

-- 
- Harald Welte ***@***.***>          https://laforge.gnumonks.org/
============================================================================
"Privacy in residential applications is a desirable marketing option."
                                                  (ETSI EN 300 175-7 Ch. A6)

**Comment by tscharly** [comment]
Wir haben bestellt: 
https://www.rittal.com/de-de/products/PG0002SCHRANK1/PG0021SCHRANK1/PGRP30564SCHRANK1/PRO100965?variantId=7646400
Lieferung in der Woche ab 17.6.24
